### ISSUE TITLE
new installation: now "instance system.adapter.awattar.0 already running with pid 2655"

### ISSUE THREAD

**Issue by derLaas** [sirjojo69/ioBroker.awattar#9]
I just installed the whole system completely new.
Now I just get the log Entry: 

"instance system.adapter.awattar.0 already running with pid 2655"

every time the instance is scheduled and it does not do anything.
The only time it works is at the very first time after a reboot.

**To Reproduce**  
1. just schedule the adapter
2. take a look in the log after a scheduled start
3. find the entry: "instance system.adapter.awattar.0 already running with pid xxxx"

**Expected behavior**  
There should not be such an error, in my old installation it works perfektly.
So my quess is it is triggered by a updated software

**Screenshots & Logfiles**  
host.raspberrypi | 2021-05-13 19:53:00.016 | warn | instance system.adapter.awattar.0 already running with pid 2655

**Versions:**  
 - Adapter version: 1.0.5
 - Node version: v12.22.1
 - Operating system: raspberian

**Comment by sirjojo69** [comment]
hi there. thx for your feedback to that new version. i will have time to investigate on that on tuesday and will then comeback with a solution ... for the moment i will revert last update...

**Comment by pmoston** [comment]
Hello, 
Is there any update on this issue? I`m facing the same problem. Basically it means, the adapter can run once, subsequent runs fail with the error mentioned above. 

host.raspberrypi | 2021-07-17 15:15:00.053 | warn | instance system.adapter.awattar.0 already running with pid 15558

Running adapter version 1.0.5
System Info:
raspberrypi
Platform: linux
Betriebssystem: linux
Architektur: arm
CPUs: 4
Geschwindigkeit: 1000 MHz
Modell: ARMv7 Processor rev 5 (v7l)
RAM: 973.76 MB
System Betriebszeit: 3 T. 15:39:01
Node.js: v12.22.2 (Es gibt eine neuere Version: v12.22.3)
NPM: 6.14.13
Festplatte Größe: 58.24 GB
Festplatte frei: 54.17 GB
Anzahl der Adapter: 348
Betriebszeit: 3 T. 15:37:27
Aktive Instanzen: 10
Hostname: raspberrypi

Best regards
Philip

**Comment by sirjojo69** [comment]
sorry, both. i just had absolutely no time for this adapter in the past months... i will take care about this issue in the next days...

**Comment by sirjojo69** [comment]
hi. there is an update for this adapter which i just pushed... on my test installation i set the schedule to trigger each minute and it worked for me. pls check for you and let me know if it works for you again. sorry again for the late response but it is due to my workload...

**Comment by derLaas** [comment]
Sorry, didn't solve the problem for me:


error | instance system.adapter.awattar.0 terminated with code 7 (ADAPTER_ALREADY_RUNNING)
-- | --

any suggestions?

**Comment by sirjojo69** [comment]
which version did you take? latest from repo or 1.0.5?

**Comment by derLaas** [comment]
> which version did you take? latest from repo or 1.0.5?

1.0.6!

But wait, I just checked the object again today. And now they are updated properly! :-)

So, it's solved for me, thnak you!
